from endpoint.views.category_type_performance import CategoryTypePerformanceView
from endpoint.views.conversion_rate import ConversionRateView
from endpoint.views.filter_and_aggregate import FilterAndAggregateView
from endpoint.views.status_based import StatusBasedView